# Generated by Django 4.0.3 on 2022-03-24 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_remove_board_member_member'),
        ('card', '0002_card_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='board_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='board.board'),
            preserve_default=False,
        ),
    ]
