# Generated by Django 4.0.3 on 2022-03-24 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0002_alter_board_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='member',
            field=models.ManyToManyField(related_name='board_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
